"use strict";

const SpellsData = `
url,name,level,tradition,school,actions,range,area,duration
Spells.aspx?ID=5,Air Bubble,1,"Arcane, Divine, Primal",Conjuration,[reaction],60 feet,,1 minute
Spells.aspx?ID=7,Alarm,1,"Arcane, Divine, Occult, Primal",Abjuration,10 minutes,touch,20-foot burst,8 hours
Spells.aspx?ID=13,Ant Haul,1,"Arcane, Primal",Transmutation,[two-actions],touch,,8 hours
Spells.aspx?ID=18,Bane,1,"Divine, Occult",Enchantment,[two-actions],,5-foot emanation,1 minute
Spells.aspx?ID=25,Bless,1,"Divine, Occult",Enchantment,[two-actions],,5-foot emanation,1 minute
Spells.aspx?ID=30,Burning Hands,1,"Arcane, Primal",Evocation,[two-actions],,15-foot cone,
Spells.aspx?ID=34,Charm,1,"Arcane, Occult, Primal",Enchantment,[two-actions],30 feet,,1 hour
Spells.aspx?ID=44,Color Spray,1,"Arcane, Occult",Illusion,[two-actions],,15-foot cone,1 or more rounds (see below)
Spells.aspx?ID=45,Command,1,"Arcane, Divine, Occult",Enchantment,[two-actions],30 feet,,until the end of the target's next turn
Spells.aspx?ID=53,Create Water,1,"Arcane, Divine, Primal",Conjuration,[two-actions],0 feet,,
Spells.aspx?ID=65,Detect Alignment,1,"Divine, Occult",Divination,[two-actions],,30-foot emanation,
Spells.aspx?ID=67,Detect Poison,1,"Divine, Primal",Divination,[two-actions],30 feet,,
Spells.aspx?ID=80,Disrupting Weapons,1,Divine,Necromancy,[two-actions],touch,,1 minute
Spells.aspx?ID=110,Fear,1,"Arcane, Divine, Occult, Primal",Enchantment,[two-actions],30 feet,,varies
Spells.aspx?ID=111,Feather Fall,1,"Arcane, Primal",Abjuration,[reaction],60 feet,,1 minute
Spells.aspx?ID=122,Fleet Step,1,"Arcane, Primal",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=124,Floating Disk,1,"Arcane, Occult",Conjuration,[two-actions],,,8 hours
Spells.aspx?ID=139,Goblin Pox,1,"Arcane, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=140,Grease,1,"Arcane, Primal",Conjuration,[two-actions],30 feet,4 contiguous 5-foot squares or,1 minute
Spells.aspx?ID=141,Grim Tendrils,1,"Arcane, Occult",Necromancy,[two-actions],,30-foot line,
Spells.aspx?ID=143,Gust of Wind,1,"Arcane, Primal",Evocation,[two-actions],,60-foot line,until the start of your next turn
Spells.aspx?ID=146,Harm,1,Divine,Necromancy,[one-action] to [three-actions],varies,,
Spells.aspx?ID=148,Heal,1,"Divine, Primal",Necromancy,[one-action] to [three-actions],varies,,
Spells.aspx?ID=154,Hydraulic Push,1,"Arcane, Primal",Evocation,[two-actions],60 feet,,
Spells.aspx?ID=159,Illusory Disguise,1,"Arcane, Occult",Illusion,[two-actions],,,1 hour
Spells.aspx?ID=160,Illusory Object,1,"Arcane, Occult",Illusion,[two-actions],500 feet,20-foot burst,10 minutes
Spells.aspx?ID=166,Item Facade,1,"Arcane, Occult",Illusion,[two-actions],touch,,1 hour
Spells.aspx?ID=167,Jump,1,"Arcane, Primal",Transmutation,[one-action],,,
Spells.aspx?ID=174,Lock,1,"Arcane, Divine, Occult",Abjuration,[two-actions],touch,,until the next time you make your daily preparations.
Spells.aspx?ID=175,Longstrider,1,"Arcane, Primal",Transmutation,[two-actions],,,1 hour
Spells.aspx?ID=176,Mage Armor,1,"Arcane, Occult, Elemental",Abjuration,[two-actions],,,until the next time you make your daily preparations
Spells.aspx?ID=178,Magic Aura,1,"Arcane, Occult",Illusion,1 minute,touch,,until the next time you make your daily preparations
Spells.aspx?ID=179,Magic Fang,1,Primal,Transmutation,[two-actions],touch,,1 minute
Spells.aspx?ID=180,Magic Missile,1,"Arcane, Occult",Evocation,[one-action] to [three-actions],120 feet,,
Spells.aspx?ID=182,Magic Weapon,1,"Arcane, Divine, Occult, Elemental",Transmutation,[two-actions],touch,,1 minute
Spells.aspx?ID=189,Mending,1,"Arcane, Divine, Occult, Primal, Elemental",Transmutation,10 minutes,touch,,
Spells.aspx?ID=195,Mindlink,1,Occult,Divination,[two-actions],touch,,
Spells.aspx?ID=206,Negate Aroma,1,"Arcane, Primal",Abjuration,[two-actions],touch,,1 hour
Spells.aspx?ID=215,Pass Without Trace,1,Primal,Abjuration,[two-actions],,,1 hour
Spells.aspx?ID=217,Pest Form,1,"Arcane, Primal",Transmutation,[two-actions],,,10 minutes
Spells.aspx?ID=220,Phantom Pain,1,Occult,Illusion,[two-actions],30 feet,,1 minute
Spells.aspx?ID=238,Protection,1,"Divine, Occult",Abjuration,[two-actions],touch,,1 minute
Spells.aspx?ID=241,Purify Food and Drink,1,"Divine, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=244,Ray of Enfeeblement,1,"Arcane, Divine, Occult",Necromancy,[two-actions],30 feet,,1 minute
Spells.aspx?ID=266,Sanctuary,1,"Divine, Occult",Abjuration,[two-actions],touch,,1 minute
Spells.aspx?ID=282,Shillelagh,1,Primal,Transmutation,[two-actions],touch,,1 minute
Spells.aspx?ID=283,Shocking Grasp,1,"Arcane, Primal",Evocation,[two-actions],touch,,
Spells.aspx?ID=288,Sleep,1,"Arcane, Occult",Enchantment,[two-actions],30 feet,5-foot burst,
Spells.aspx?ID=291,Soothe,1,Occult,Enchantment,[two-actions],30 feet,,1 minute
Spells.aspx?ID=300,Spider Sting,1,"Arcane, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=302,Spirit Link,1,"Divine, Occult",Necromancy,[two-actions],30 feet,,10 minutes
Spells.aspx?ID=316,Summon Animal,1,"Arcane, Primal",Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=318,Summon Construct,1,Arcane,Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=322,Summon Fey,1,"Occult, Primal",Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=325,Summon Plant or Fungus,1,Primal,Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=345,True Strike,1,"Arcane, Occult",Divination,[one-action],,,until the end of your turn
Spells.aspx?ID=352,Unseen Servant,1,"Arcane, Occult",Conjuration,[three-actions],60 feet,,sustained
Spells.aspx?ID=356,Ventriloquism,1,"Arcane, Divine, Occult, Primal, Elemental",Illusion,[two-actions],,,10 minutes
Spells.aspx?ID=2,Acid Arrow,2,"Arcane, Primal",Evocation,[two-actions],120 feet,,
Spells.aspx?ID=10,Animal Form,2,Primal,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=11,Animal Messenger,2,Primal,Enchantment,1 minute,120 feet,,see text
Spells.aspx?ID=15,Augury,2,"Divine, Occult",Divination,10 minutes,,,
Spells.aspx?ID=20,Barkskin,2,Primal,Abjuration,[two-actions],touch,,10 minutes
Spells.aspx?ID=28,Blur,2,"Arcane, Occult",Illusion,[two-actions],touch,,1 minute
Spells.aspx?ID=31,Calm Emotions,2,"Divine, Occult",Enchantment,[two-actions],120 feet,10-foot burst,sustained up to 1 minute
Spells.aspx?ID=46,Comprehend Language,2,"Arcane, Divine, Occult",Divination,[two-actions],30 feet,,1 hour
Spells.aspx?ID=50,Continual Flame,2,"Arcane, Divine, Occult, Primal",Evocation,[three-actions],touch,,unlimited
Spells.aspx?ID=52,Create Food,2,"Arcane, Divine, Primal",Conjuration,1 hour,30 feet,,
Spells.aspx?ID=59,Darkness,2,"Arcane, Divine, Occult, Primal",Evocation,[three-actions],120 feet,20-foot burst,1 minute
Spells.aspx?ID=60,Darkvision,2,"Arcane, Divine, Occult, Primal, Elemental",Divination,[two-actions],,,1 hour
Spells.aspx?ID=62,Deafness,2,"Arcane, Divine, Occult, Primal",Necromancy,[two-actions],30 feet,,
Spells.aspx?ID=63,Death Knell,2,"Divine, Occult",Necromancy,[two-actions],touch,,
Spells.aspx?ID=78,Dispel Magic,2,"Arcane, Divine, Occult, Primal, Elemental",Abjuration,[two-actions],120 feet,,
Spells.aspx?ID=99,Endure Elements,2,"Arcane, Divine, Primal, Elemental",Abjuration,10 minutes,touch,,until the next time you make your daily preparations
Spells.aspx?ID=101,Enhance Victuals,2,"Divine, Primal",Transmutation,1 minute,touch,,1 hour
Spells.aspx?ID=102,Enlarge,2,"Arcane, Primal",Transmutation,[two-actions],30 feet,,5 minutes
Spells.aspx?ID=103,Entangle,2,Primal,Transmutation,[two-actions],120 feet,all squares in a 20-foot-radius burst that contain plants or fungi,1 minute
Spells.aspx?ID=107,Faerie Fire,2,"Divine, Occult, Primal, Elemental",Evocation,[two-actions],120 feet,10-foot burst,5 minutes
Spells.aspx?ID=108,False Life,2,"Arcane, Occult",Necromancy,[two-actions],,,8 hours
Spells.aspx?ID=121,Flaming Sphere,2,"Arcane, Primal",Evocation,[two-actions],30 feet,1 5-foot square,sustained up to 1 minute
Spells.aspx?ID=131,Gentle Repose,2,"Arcane, Divine, Occult, Primal, Elemental",Necromancy,[two-actions],touch,,until the next time you make your daily preparations
Spells.aspx?ID=134,Ghoulish Cravings,2,"Divine, Occult",Necromancy,[two-actions],touch,,
Spells.aspx?ID=136,Glitterdust,2,"Arcane, Primal",Evocation,[two-actions],120 feet,10-foot burst,
Spells.aspx?ID=150,Hideous Laughter,2,"Arcane, Occult",Enchantment,[two-actions],30 feet,,sustained
Spells.aspx?ID=153,Humanoid Form,2,"Arcane, Occult, Primal",Transmutation,[two-actions],,,10 minutes
Spells.aspx?ID=158,Illusory Creature,2,"Arcane, Occult",Illusion,[two-actions],500 feet,,sustained
Spells.aspx?ID=164,Invisibility,2,"Arcane, Occult",Illusion,[two-actions],touch,,10 minutes
Spells.aspx?ID=168,Knock,2,"Arcane, Occult",Transmutation,[two-actions],30 feet,,1 minute
Spells.aspx?ID=181,Magic Mouth,2,"Arcane, Occult",Illusion,[two-actions],touch,,unlimited
Spells.aspx?ID=197,Mirror Image,2,"Arcane, Occult",Illusion,[two-actions],,,1 minute
Spells.aspx?ID=198,Misdirection,2,"Arcane, Occult",Illusion,1 minute,30 feet,,until the next time you make your daily preparations
Spells.aspx?ID=210,Obscuring Mist,2,"Arcane, Primal",Conjuration,[three-actions],120 feet,20-foot burst,1 minute
Spells.aspx?ID=214,Paranoia,2,Occult,Illusion,[two-actions],30 feet,,1 minute
Spells.aspx?ID=221,Phantom Steed,2,"Arcane, Occult, Primal",Conjuration,10 minutes,30 feet,,8 hours
Spells.aspx?ID=252,Remove Fear,2,"Divine, Occult, Primal",Enchantment,[two-actions],touch,,
Spells.aspx?ID=253,Remove Paralysis,2,"Divine, Occult, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=256,Resist Energy,2,"Arcane, Divine, Occult, Primal, Elemental",Abjuration,[two-actions],touch,,10 minutes
Spells.aspx?ID=258,Restoration,2,"Divine, Occult, Primal",Necromancy,1 minute,touch,,
Spells.aspx?ID=259,Restore Senses,2,"Divine, Occult, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=271,See Invisibility,2,"Arcane, Divine, Occult",Divination,[two-actions],,,10 minutes
Spells.aspx?ID=277,Shape Wood,2,Primal,Transmutation,[two-actions],touch,,
Spells.aspx?ID=279,Shatter,2,"Occult, Primal",Evocation,[two-actions],30 feet,,
Spells.aspx?ID=281,Shield Other,2,Divine,Necromancy,[two-actions],30 feet,,10 minutes
Spells.aspx?ID=284,Shrink,2,"Arcane, Primal",Transmutation,[two-actions],30 feet,,5 minutes
Spells.aspx?ID=287,Silence,2,"Divine, Occult",Illusion,[two-actions],touch,,1 minute
Spells.aspx?ID=292,Sound Burst,2,"Divine, Occult",Evocation,[two-actions],30 feet,10-foot burst,
Spells.aspx?ID=293,Speak with Animals,2,Primal,Divination,[two-actions],,,10 minutes
Spells.aspx?ID=295,Spectral Hand,2,"Arcane, Occult",Necromancy,[two-actions],120 feet,,1 minute
Spells.aspx?ID=299,Spider Climb,2,"Arcane, Primal",Transmutation,[two-actions],touch,,10 minutes
Spells.aspx?ID=306,Spiritual Weapon,2,"Divine, Occult",Evocation,[two-actions],120 feet,,sustained up to 1 minute
Spells.aspx?ID=308,Status,2,"Divine, Occult, Primal",Divination,[two-actions],touch,,until the next time you make your daily preparations.
Spells.aspx?ID=320,Summon Elemental,2,"Arcane, Primal, Elemental",Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=333,Telekinetic Maneuver,2,"Arcane, Occult",Evocation,[two-actions],60 feet,,
Spells.aspx?ID=341,Touch of Idiocy,2,"Arcane, Occult",Enchantment,[two-actions],touch,,1 minute
Spells.aspx?ID=342,Tree Shape,2,Primal,Transmutation,[two-actions],,,8 hours
Spells.aspx?ID=348,Undetectable Alignment,2,"Divine, Occult",Abjuration,1 minute,touch,,until the next time you make your daily preparations
Spells.aspx?ID=370,Water Breathing,2,"Arcane, Divine, Primal",Transmutation,1 minute,30 feet,,1 hour
Spells.aspx?ID=371,Water Walk,2,"Arcane, Divine, Primal",Transmutation,[two-actions],touch,,10 minutes
Spells.aspx?ID=374,Web,2,"Arcane, Primal",Conjuration,[three-actions],30 feet,10-foot burst,1 minute
Spells.aspx?ID=12,Animal Vision,3,Primal,Divination,1 minute,120 feet,,1 hour
Spells.aspx?ID=22,Bind Undead,3,"Arcane, Divine, Occult",Necromancy,[two-actions],30 feet,,1 day
Spells.aspx?ID=26,Blindness,3,"Arcane, Divine, Occult, Primal",Necromancy,[two-actions],30 feet,,
Spells.aspx?ID=36,Chilling Darkness,3,Divine,Evocation,[two-actions],120 feet,,
Spells.aspx?ID=38,Circle of Protection,3,"Divine, Occult",Abjuration,[three-actions],touch,10-foot emanation centered on the touched creature,1 minute
Spells.aspx?ID=39,Clairaudience,3,"Arcane, Occult",Divination,1 minute,500 feet,,10 minutes
Spells.aspx?ID=55,Crisis of Faith,3,Divine,Enchantment,[two-actions],30 feet,,
Spells.aspx?ID=90,Dream Message,3,"Arcane, Divine, Occult",Enchantment,10 minutes,planetary,,until the next time you make your daily preparations.
Spells.aspx?ID=94,Earthbind,3,"Arcane, Primal",Transmutation,[two-actions],120 feet,,varies
Spells.aspx?ID=104,Enthrall,3,"Arcane, Occult",Enchantment,[two-actions],120 feet,,sustained
Spells.aspx?ID=113,Feet to Fins,3,"Arcane, Primal",Transmutation,[two-actions],touch,,10 minutes
Spells.aspx?ID=119,Fireball,3,"Arcane, Primal",Evocation,[two-actions],500 feet,20-foot burst,
Spells.aspx?ID=133,Ghostly Weapon,3,"Arcane, Occult",Transmutation,[two-actions],touch,,5 minutes
Spells.aspx?ID=138,Glyph of Warding,3,"Arcane, Divine, Occult, Primal",Abjuration,10 minutes,touch,,unlimited
Spells.aspx?ID=147,Haste,3,"Arcane, Occult, Primal",Transmutation,[two-actions],30 feet,,1 minute
Spells.aspx?ID=149,Heroism,3,"Divine, Occult",Enchantment,[two-actions],touch,,10 minutes
Spells.aspx?ID=156,Hypercognition,3,Occult,Divination,[one-action],,,
Spells.aspx?ID=157,Hypnotic Pattern,3,"Arcane, Occult",Illusion,[two-actions],120 feet,10-foot burst,sustained up to 1 minute
Spells.aspx?ID=163,Insect Form,3,Primal,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=165,Invisibility Sphere,3,"Arcane, Occult",Illusion,[two-actions],,10-foot emanation,10 minutes
Spells.aspx?ID=170,Levitate,3,"Arcane, Occult, Elemental",Evocation,[two-actions],touch,,5 minutes
Spells.aspx?ID=172,Lightning Bolt,3,"Arcane, Primal",Evocation,[two-actions],,120-foot line,
Spells.aspx?ID=173,Locate,3,"Arcane, Divine, Occult",Divination,10 minutes,500 feet,,sustained
Spells.aspx?ID=188,Meld into Stone,3,"Arcane, Primal",Transmutation,[two-actions],,,10 minutes
Spells.aspx?ID=194,Mind Reading,3,"Arcane, Occult",Divination,[two-actions],30 feet,,1 round or sustained up to 1 minute
Spells.aspx?ID=207,Neutralize Poison,3,"Divine, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=209,Nondetection,3,"Arcane, Occult, Primal",Abjuration,10 minutes,touch,,8 hours
Spells.aspx?ID=213,Paralyze,3,"Arcane, Occult",Enchantment,[two-actions],30 feet,,varies
Spells.aspx?ID=251,Remove Disease,3,"Divine, Primal",Necromancy,10 minutes,touch,,
Spells.aspx?ID=265,Sanctified Ground,3,Divine,Abjuration,1 minute,,30-foot burst centered on you,until the next time you make your daily preparations.
Spells.aspx?ID=269,Searing Light,3,"Divine, Primal",Evocation,[two-actions],120 feet,,
Spells.aspx?ID=270,Secret Page,3,"Arcane, Occult",Illusion,1 minute,touch,,unlimited
Spells.aspx?ID=285,Shrink Item,3,Arcane,Transmutation,10 minutes,touch,,until the next time you make your daily preparations.
Spells.aspx?ID=289,Slow,3,"Arcane, Occult, Primal",Transmutation,[two-actions],30 feet,,1 minute
Spells.aspx?ID=309,Stinking Cloud,3,"Arcane, Primal",Conjuration,[two-actions],120 feet,20-foot burst,1 minute
Spells.aspx?ID=354,Vampiric Touch,3,"Arcane, Divine, Occult",Necromancy,[two-actions],touch,,
Spells.aspx?ID=366,Wall of Thorns,3,Primal,Conjuration,[three-actions],60 feet,,1 minute
Spells.aspx?ID=367,Wall of Wind,3,"Arcane, Primal",Evocation,[three-actions],120 feet,,1 minute
Spells.aspx?ID=368,Wanderer's Guide,3,"Divine, Occult",Divination,1 minute,,,until your next daily preparations
Spells.aspx?ID=379,Zone of Truth,3,"Divine, Occult",Enchantment,[two-actions],30 feet,20-foot burst,10 minutes
Spells.aspx?ID=4,Aerial Form,4,"Arcane, Primal",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=6,Air Walk,4,"Divine, Primal",Transmutation,[two-actions],touch,,5 minutes
Spells.aspx?ID=9,Anathematic Reprisal,4,Divine,Enchantment,[reaction],30 feet,,
Spells.aspx?ID=27,Blink,4,"Arcane, Occult",Conjuration,[two-actions],,,1 minute
Spells.aspx?ID=40,Clairvoyance,4,"Arcane, Occult",Divination,1 minute,500 feet,,10 minutes
Spells.aspx?ID=48,Confusion,4,"Arcane, Occult",Enchantment,[two-actions],30 feet,,1 minute
Spells.aspx?ID=54,Creation,4,"Arcane, Primal",Conjuration,1 minute,0 feet,,1 hour
Spells.aspx?ID=68,Detect Scrying,4,"Arcane, Occult",Divination,[two-actions],,30-foot emanation,1 hour
Spells.aspx?ID=69,Dimension Door,4,"Arcane, Occult",Conjuration,[two-actions],120 feet,,
Spells.aspx?ID=70,Dimensional Anchor,4,"Arcane, Divine, Occult",Abjuration,[two-actions],30 feet,,varies
Spells.aspx?ID=72,Dinosaur Form,4,Primal,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=74,Discern Lies,4,"Arcane, Divine, Occult",Divination,[two-actions],,,10 minutes
Spells.aspx?ID=86,Divine Wrath,4,Divine,Evocation,[two-actions],120 feet,20-foot burst,
Spells.aspx?ID=118,Fire Shield,4,"Arcane, Primal",Evocation,[two-actions],,,1 minute
Spells.aspx?ID=125,Fly,4,"Arcane, Occult, Primal, Elemental",Transmutation,[two-actions],touch,,5 minutes
Spells.aspx?ID=128,Freedom of Movement,4,"Arcane, Divine, Primal",Abjuration,[two-actions],touch,,10 minutes
Spells.aspx?ID=129,Gaseous Form,4,"Arcane, Occult, Primal",Transmutation,[two-actions],touch,,5 minutes
Spells.aspx?ID=135,Glibness,4,Occult,Enchantment,[two-actions],,,10 minutes
Spells.aspx?ID=137,Globe of Invulnerability,4,"Arcane, Divine, Occult",Abjuration,[two-actions],,10-foot burst centered on one corner of your space,10 minutes
Spells.aspx?ID=145,Hallucinatory Terrain,4,"Arcane, Occult, Primal",Illusion,10 minutes,500 feet,50-foot burst,until the next time you make your daily preparations
Spells.aspx?ID=151,Holy Cascade,4,Divine,Evocation,[two-actions],500 feet,20-foot burst,
Spells.aspx?ID=155,Hydraulic Torrent,4,Primal,Evocation,[two-actions],,60-foot line,
Spells.aspx?ID=200,Modify Memory,4,Occult,Divination,[two-actions],30 feet,,unlimited
Spells.aspx?ID=208,Nightmare,4,"Arcane, Occult",Illusion,10 minutes,planetary,,1 day
Spells.aspx?ID=211,Outcast's Curse,4,"Arcane, Divine, Occult",Enchantment,[two-actions],touch,,
Spells.aspx?ID=219,Phantasmal Killer,4,"Arcane, Occult",Illusion,[two-actions],120 feet,,
Spells.aspx?ID=235,Private Sanctum,4,"Arcane, Occult",Abjuration,10 minutes,touch,100-foot burst,until the next time you make your daily preparations.
Spells.aspx?ID=247,Read Omens,4,"Divine, Occult",Divination,10 minutes,,,
Spells.aspx?ID=250,Remove Curse,4,"Divine, Occult",Necromancy,10 minutes,touch,,
Spells.aspx?ID=255,Resilient Sphere,4,"Arcane, Occult",Abjuration,[two-actions],30 feet,,1 minute
Spells.aspx?ID=264,Rope Trick,4,"Arcane, Occult",Conjuration,10 minutes,touch,,8 hours
Spells.aspx?ID=276,Shape Stone,4,"Arcane, Primal",Transmutation,[two-actions],touch,,
Spells.aspx?ID=290,Solid Fog,4,"Arcane, Primal",Conjuration,[three-actions],120 feet,20-foot burst,1 minute
Spells.aspx?ID=294,Speak with Plants,4,Primal,Divination,[two-actions],,,10 minutes
Spells.aspx?ID=296,Spell Immunity,4,"Arcane, Divine, Occult",Abjuration,[two-actions],touch,,until the next time you make your daily preparations.
Spells.aspx?ID=312,Stoneskin,4,"Arcane, Primal",Abjuration,[two-actions],touch,,20 minutes
Spells.aspx?ID=315,Suggestion,4,"Arcane, Occult",Enchantment,[two-actions],30 feet,,varies
Spells.aspx?ID=329,Talking Corpse,4,"Divine, Occult",Necromancy,10 minutes,touch,,10 minutes
Spells.aspx?ID=337,Telepathy,4,"Arcane, Occult",Divination,[two-actions],,,10 minutes
Spells.aspx?ID=355,Veil,4,"Arcane, Occult",Illusion,[two-actions],30 feet,,1 hour
Spells.aspx?ID=359,Vital Beacon,4,"Divine, Primal",Necromancy,1 minute,,,until your next daily preparations
Spells.aspx?ID=362,Wall of Fire,4,"Arcane, Primal",Evocation,[three-actions],120 feet,,1 minute
Spells.aspx?ID=373,Weapon Storm,4,"Arcane, Primal",Evocation,[two-actions],,30-foot cone or 10-foot emanation,
Spells.aspx?ID=1,Abyssal Plague,5,"Divine, Occult",Necromancy,[two-actions],touch,,
Spells.aspx?ID=19,Banishment,5,"Arcane, Divine, Occult, Primal, Elemental",Abjuration,[two-actions],30 feet,,
Spells.aspx?ID=23,Black Tentacles,5,"Arcane, Occult",Conjuration,[three-actions],120 feet,20-foot burst adjacent to a flat surface,1 minute
Spells.aspx?ID=29,Breath of Life,5,Divine,Necromancy,[reaction],60 feet,,
Spells.aspx?ID=37,Chromatic Wall,5,"Arcane, Occult",Abjuration,[three-actions],120 feet,,10 minutes
Spells.aspx?ID=41,Cloak of Colors,5,"Arcane, Occult",Illusion,[two-actions],30 feet,,1 minute
Spells.aspx?ID=42,Cloudkill,5,"Arcane, Primal",Necromancy,[three-actions],120 feet,20-foot burst,1 minute
Spells.aspx?ID=47,Cone of Cold,5,"Arcane, Primal",Evocation,[two-actions],,60-foot cone,
Spells.aspx?ID=51,Control Water,5,"Arcane, Primal",Evocation,[two-actions],500 feet,50 feet long by 50 feet wide,
Spells.aspx?ID=57,Crushing Despair,5,"Arcane, Occult",Enchantment,[two-actions],,30-foot cone,1 or more rounds
Spells.aspx?ID=64,Death Ward,5,"Divine, Occult, Primal",Abjuration,[two-actions],touch,,10 minutes
Spells.aspx?ID=91,Dreaming Potential,5,Occult,Enchantment,10 minutes,touch,,8 hours
Spells.aspx?ID=92,Drop Dead,5,"Arcane, Divine",Illusion,[reaction],120 feet,,sustained up to 1 minute
Spells.aspx?ID=98,Elemental Form,5,"Arcane, Primal, Elemental",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=109,False Vision,5,"Arcane, Occult",Illusion,10 minutes,touch,100-foot burst,until the next time you make your daily preparations
Spells.aspx?ID=120,Flame Strike,5,Divine,Evocation,[two-actions],120 feet,"10-foot radius, 40-foot-tall cylinder",
Spells.aspx?ID=144,Hallucination,5,"Arcane, Occult",Illusion,[two-actions],30 feet,,1 hour
Spells.aspx?ID=161,Illusory Scene,5,"Arcane, Occult",Illusion,10 minutes,500 feet,30-foot burst,1 hour
Spells.aspx?ID=184,Mariner's Curse,5,"Arcane, Occult, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=193,Mind Probe,5,"Arcane, Occult",Divination,1 minute,30 feet,,sustained up to 1 minute
Spells.aspx?ID=203,Moon Frenzy,5,Primal,Transmutation,[two-actions],30 feet,,1 minute
Spells.aspx?ID=216,Passwall,5,"Arcane, Primal",Conjuration,[two-actions],touch,"5-foot-wide, 10-foot-tall, 10-foot deep section of wooden, plaster, or stone wall",1 hour
Spells.aspx?ID=223,Plant Form,5,Primal,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=239,Prying Eye,5,"Arcane, Divine, Occult",Divination,1 minute,see text,,sustained
Spells.aspx?ID=272,Sending,5,"Arcane, Divine, Occult",Divination,[three-actions],planetary,,
Spells.aspx?ID=273,Shadow Blast,5,"Divine, Occult",Evocation,[two-actions],varies,varies,
Spells.aspx?ID=274,Shadow Siphon,5,"Arcane, Occult",Illusion,[reaction],60 feet,,
Spells.aspx?ID=275,Shadow Walk,5,"Arcane, Occult",Conjuration,1 minute,touch,,8 hours
Spells.aspx?ID=305,Spiritual Guardian,5,Divine,Abjuration,[two-actions],120 feet,,sustained up to 1 minute
Spells.aspx?ID=314,Subconscious Suggestion,5,"Arcane, Occult",Enchantment,[two-actions],30 feet,,varies
Spells.aspx?ID=317,Summon Celestial,5,Divine,Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=319,Summon Dragon,5,Arcane,Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=321,Summon Entity,5,Occult,Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=323,Summon Fiend,5,Divine,Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=324,Summon Giant,5,"Primal, Elemental",Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=327,Synaptic Pulse,5,Occult,Enchantment,[two-actions],,30-foot emanation,1 round
Spells.aspx?ID=328,Synesthesia,5,Occult,Divination,[two-actions],30 feet,,1 minute
Spells.aspx?ID=332,Telekinetic Haul,5,"Arcane, Occult",Evocation,[two-actions],120 feet,,sustained up to 1 minute
Spells.aspx?ID=335,Telepathic Bond,5,"Arcane, Occult",Divination,1 minute,touch,,8 hours
Spells.aspx?ID=340,Tongues,5,"Arcane, Divine, Occult",Divination,[two-actions],touch,,1 hour
Spells.aspx?ID=343,Tree Stride,5,Primal,Conjuration,1 minute,,,
Spells.aspx?ID=364,Wall of Ice,5,"Arcane, Primal",Evocation,[three-actions],120 feet,,1 minute
Spells.aspx?ID=365,Wall of Stone,5,"Arcane, Primal",Conjuration,[three-actions],120 feet,,
Spells.aspx?ID=17,Baleful Polymorph,6,"Arcane, Primal",Transmutation,[two-actions],30 feet,,varies
Spells.aspx?ID=24,Blade Barrier,6,Divine,Evocation,[three-actions],120 feet,,1 minute
Spells.aspx?ID=33,Chain Lightning,6,"Arcane, Primal",Evocation,[two-actions],500 feet,,
Spells.aspx?ID=43,Collective Transposition,6,"Arcane, Occult",Conjuration,[two-actions],,30-foot emanation,
Spells.aspx?ID=76,Disintegrate,6,Arcane,Evocation,[two-actions],120 feet,,
Spells.aspx?ID=87,Dominate,6,"Arcane, Occult",Enchantment,[two-actions],30 feet,,until the next time you make your daily preparations
Spells.aspx?ID=88,Dragon Form,6,"Arcane, Primal",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=112,Feeblemind,6,"Arcane, Occult",Enchantment,[two-actions],30 feet,,varies
Spells.aspx?ID=114,Field of Life,6,"Divine, Primal",Necromancy,[two-actions],30 feet,20-foot burst,sustained up to 1 minute
Spells.aspx?ID=117,Fire Seeds,6,Primal,Evocation,[two-actions],,,1 minute
Spells.aspx?ID=123,Flesh to Stone,6,"Arcane, Primal",Transmutation,[two-actions],120 feet,,varies
Spells.aspx?ID=199,Mislead,6,"Arcane, Occult",Illusion,[two-actions],,,sustained up to 1 minute
Spells.aspx?ID=218,Phantasmal Calamity,6,"Arcane, Occult",Illusion,[two-actions],500 feet,30-foot burst,
Spells.aspx?ID=242,Purple Worm Sting,6,"Arcane, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=243,Raise Dead,6,Divine,Necromancy,10 minutes,10 feet,,
Spells.aspx?ID=254,Repulsion,6,"Arcane, Divine, Occult",Abjuration,[two-actions],emanation up to 40-feet,,1 minute
Spells.aspx?ID=263,Righteous Might,6,Divine,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=268,Scrying,6,"Arcane, Occult",Divination,10 minutes,planetary,,sustained up to 10 minutes
Spells.aspx?ID=298,Spellwrack,6,"Arcane, Divine, Occult",Abjuration,[two-actions],30 feet,,
Spells.aspx?ID=301,Spirit Blast,6,"Divine, Occult",Necromancy,[two-actions],30 feet,,
Spells.aspx?ID=310,Stone Tell,6,"Divine, Primal",Evocation,[two-actions],,,10 minutes
Spells.aspx?ID=311,Stone to Flesh,6,"Divine, Primal",Transmutation,[two-actions],touch,,
Spells.aspx?ID=331,Tangling Creepers,6,Primal,Conjuration,[three-actions],500 feet,40-foot burst,10 minutes
Spells.aspx?ID=338,Teleport,6,"Arcane, Occult, Elemental",Conjuration,10 minutes,100 miles,,
Spells.aspx?ID=344,True Seeing,6,"Arcane, Divine, Occult, Primal, Elemental",Divination,[two-actions],,,10 minutes
Spells.aspx?ID=353,Vampiric Exsanguination,6,"Arcane, Divine, Occult",Necromancy,[two-actions],,30-foot cone,
Spells.aspx?ID=357,Vibrant Pattern,6,"Arcane, Occult",Illusion,[two-actions],120 feet,10-foot burst,sustained up to 1 minute
Spells.aspx?ID=363,Wall of Force,6,"Arcane, Occult",Evocation,[three-actions],30 feet,,1 minute
Spells.aspx?ID=378,Zealous Conviction,6,"Divine, Occult",Enchantment,[two-actions],30 feet,,10 minutes
Spells.aspx?ID=49,Contingency,7,Arcane,Abjuration,10 minutes,,,until the next time you make your daily preparations.
Spells.aspx?ID=71,Dimensional Lock,7,"Arcane, Divine, Occult, Elemental",Abjuration,[two-actions],120 feet,60-foot burst,until the next time you make your daily preparations.
Spells.aspx?ID=82,Divine Decree,7,Divine,Evocation,[two-actions],40 feet,40-foot emanation,varies
Spells.aspx?ID=85,Divine Vessel,7,Divine,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=93,Duplicate Foe,7,"Arcane, Occult",Conjuration,[three-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=96,Eclipse Burst,7,"Arcane, Divine, Primal",Necromancy,[two-actions],500 feet,60-foot burst,
Spells.aspx?ID=100,Energy Aegis,7,"Arcane, Divine, Occult, Primal, Elemental",Abjuration,1 minute,touch,,until the next time you make your daily preparations.
Spells.aspx?ID=105,Ethereal Jaunt,7,"Divine, Occult",Conjuration,[two-actions],,,sustained up to 1 minute
Spells.aspx?ID=115,Fiery Body,7,"Arcane, Primal",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=116,Finger of Death,7,"Divine, Primal",Necromancy,[two-actions],30 feet,,
Spells.aspx?ID=183,Magnificent Mansion,7,"Arcane, Occult",Conjuration,1 minute,30 feet,,until the next time you make your daily preparations.
Spells.aspx?ID=185,Mask of Terror,7,"Arcane, Occult, Primal",Illusion,[two-actions],30 feet,,1 minute
Spells.aspx?ID=222,Plane Shift,7,"Arcane, Divine, Occult, Primal, Elemental",Conjuration,10 minutes,touch,,
Spells.aspx?ID=225,Possession,7,Occult,Necromancy,[two-actions],30 feet,,1 minute
Spells.aspx?ID=226,Power Word Blind,7,Arcane,Enchantment,[one-action],30 feet,,varies
Spells.aspx?ID=233,Prismatic Spray,7,"Arcane, Occult",Evocation,[two-actions],,30-foot cone,
Spells.aspx?ID=237,Project Image,7,"Arcane, Occult",Illusion,[two-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=248,Regenerate,7,"Divine, Primal",Necromancy,[two-actions],touch,,1 minute
Spells.aspx?ID=260,Retrocognition,7,Occult,Divination,1 minute,,,sustained
Spells.aspx?ID=261,Reverse Gravity,7,"Arcane, Occult",Evocation,[three-actions],120 feet,"20-foot radius, 40-foot-tall cylinder",1 minute
Spells.aspx?ID=297,Spell Turning,7,Arcane,Abjuration,[two-actions],,,1 hour
Spells.aspx?ID=326,Sunburst,7,"Divine, Primal",Evocation,[two-actions],500 feet,60-foot burst,
Spells.aspx?ID=346,True Target,7,"Arcane, Occult",Divination,[one-action],60 feet,,until the start of your next turn
Spells.aspx?ID=350,Unfettered Pack,7,"Primal, Elemental",Abjuration,[two-actions],30 feet,,1 hour
Spells.aspx?ID=358,Visions of Danger,7,Occult,Illusion,[three-actions],500 feet,30-foot burst,1 minute
Spells.aspx?ID=360,Volcanic Eruption,7,Primal,Evocation,[two-actions],120 feet,"5-foot radius, 80-foot tall cylinder",
Spells.aspx?ID=369,Warp Mind,7,"Arcane, Occult",Enchantment,[two-actions],120 feet,,
Spells.aspx?ID=14,Antimagic Field,8,"Arcane, Divine, Occult",Abjuration,[three-actions],,"10-foot emanation, which affects you",sustained up to 1 minute
Spells.aspx?ID=73,Disappearance,8,"Arcane, Occult",Illusion,[two-actions],touch,,10 minutes
Spells.aspx?ID=75,Discern Location,8,"Arcane, Divine, Occult",Divination,10 minutes,unlimited,,
Spells.aspx?ID=81,Divine Aura,8,Divine,Abjuration,[two-actions],,10-foot emanation,sustained up to 1 minute
Spells.aspx?ID=83,Divine Inspiration,8,Divine,Enchantment,[two-actions],touch,,
Spells.aspx?ID=89,Dream Council,8,"Arcane, Occult",Illusion,10 minutes,planetary,,1 hour
Spells.aspx?ID=95,Earthquake,8,"Arcane, Primal",Evocation,[two-actions],500 feet,60-foot burst,1 round
Spells.aspx?ID=152,Horrid Wilting,8,"Arcane, Primal",Necromancy,[two-actions],500 feet,,
Spells.aspx?ID=187,Maze,8,"Arcane, Occult",Conjuration,[two-actions],30 feet,,sustained
Spells.aspx?ID=192,Mind Blank,8,"Arcane, Occult",Abjuration,[two-actions],30 feet,,until the next time you make your daily preparations
Spells.aspx?ID=201,Moment of Renewal,8,"Divine, Primal",Necromancy,[two-actions],touch,,
Spells.aspx?ID=202,Monstrosity Form,8,"Arcane, Primal",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=224,Polar Ray,8,"Arcane, Primal",Evocation,[two-actions],120 feet,,
Spells.aspx?ID=228,Power Word Stun,8,Arcane,Enchantment,[one-action],30 feet,,varies
Spells.aspx?ID=234,Prismatic Wall,8,"Arcane, Occult",Abjuration,[three-actions],120 feet,,1 hour
Spells.aspx?ID=240,Punishing Winds,8,Primal,Evocation,[three-actions],100 feet,"30-foot radius, 100-foot-cylinder",sustained up to 1 minute
Spells.aspx?ID=267,Scintillating Pattern,8,"Arcane, Occult",Illusion,[two-actions],120 feet,20-foot burst,sustained up to 1 minute
Spells.aspx?ID=303,Spirit Song,8,Occult,Necromancy,[two-actions],,60-foot cone,
Spells.aspx?ID=304,Spiritual Epidemic,8,"Divine, Occult",Necromancy,[two-actions],120 feet,,varies
Spells.aspx?ID=347,Uncontrollable Dance,8,"Arcane, Occult",Enchantment,[two-actions],touch,,varies
Spells.aspx?ID=351,Unrelenting Observation,8,"Arcane, Occult",Divination,[two-actions],100 feet,20-foot burst,varies
Spells.aspx?ID=376,Wind Walk,8,Primal,Transmutation,10 minutes,touch,,8 hours
Spells.aspx?ID=21,Bind Soul,9,"Divine, Occult",Necromancy,[two-actions],30 feet,,unlimited
Spells.aspx?ID=56,Crusade,9,Divine,Enchantment,[two-actions],60 feet,,10 minutes
Spells.aspx?ID=77,Disjunction,9,"Arcane, Primal",Abjuration,[two-actions],120 feet,,
Spells.aspx?ID=127,Foresight,9,"Arcane, Divine, Occult",Divination,[two-actions],touch,,1 hour
Spells.aspx?ID=162,Implosion,9,"Arcane, Primal",Evocation,[two-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=186,Massacre,9,"Arcane, Divine, Primal",Necromancy,[two-actions],,60-foot line,
Spells.aspx?ID=191,Meteor Swarm,9,"Arcane, Primal",Evocation,[two-actions],500 feet,4 40-foot bursts,
Spells.aspx?ID=205,Nature's Enmity,9,Primal,Enchantment,[two-actions],120 feet,500-foot burst,10 minutes
Spells.aspx?ID=212,Overwhelming Presence,9,"Divine, Occult",Enchantment,[two-actions],,40-foot burst,until full tribute is paid
Spells.aspx?ID=227,Power Word Kill,9,Arcane,Enchantment,[one-action],30 feet,,varies
Spells.aspx?ID=232,Prismatic Sphere,9,"Arcane, Occult",Abjuration,[two-actions],10 feet,,1 hour
Spells.aspx?ID=257,Resplendent Mansion,9,"Arcane, Occult",Conjuration,1 minute,500 feet,,until the next time you make your daily preparations
Spells.aspx?ID=278,Shapechange,9,"Arcane, Primal",Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=313,Storm of Vengeance,9,"Primal, Elemental",Evocation,[three-actions],800 feet,360-foot burst,sustained up to 1 minute
Spells.aspx?ID=336,Telepathic Demand,9,"Arcane, Divine, Occult",Enchantment,[three-actions],planetary,,varies
Spells.aspx?ID=349,Unfathomable Song,9,Occult,Enchantment,[two-actions],120 feet,,sustained up to 1 minute
Spells.aspx?ID=361,Wail of the Banshee,9,"Divine, Occult",Necromancy,[two-actions],,40-foot emanation,
Spells.aspx?ID=372,Weapon of Judgment,9,Divine,Evocation,[two-actions],100 feet,,1 minute
Spells.aspx?ID=375,Weird,9,"Arcane, Occult",Illusion,[two-actions],120 feet,,
Spells.aspx?ID=8,Alter Reality,10,Occult,Divination,[three-actions],,,
Spells.aspx?ID=16,Avatar,10,Divine,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=32,Cataclysm,10,"Arcane, Primal, Elemental",Evocation,[two-actions],"1,000 feet",60-foot burst,
Spells.aspx?ID=106,Fabricated Truth,10,Occult,Enchantment,[three-actions],100 feet,,varies
Spells.aspx?ID=130,Gate,10,"Arcane, Divine, Occult, Elemental",Conjuration,[two-actions],120 feet,,sustained up to 1 minute
Spells.aspx?ID=196,Miracle,10,Divine,Divination,[three-actions],,,
Spells.aspx?ID=204,Nature Incarnate,10,Primal,Transmutation,[two-actions],,,1 minute
Spells.aspx?ID=230,Primal Herd,10,Primal,Transmutation,[two-actions],30 feet,,1 minute
Spells.aspx?ID=231,Primal Phenomenon,10,Primal,Divination,[three-actions],,,
Spells.aspx?ID=249,Remake,10,"Arcane, Divine, Occult, Primal, Elemental",Conjuration,1 hour,5 feet,,
Spells.aspx?ID=262,Revival,10,"Divine, Primal",Necromancy,[two-actions],30 feet,,sustained up to 1 minute
Spells.aspx?ID=339,Time Stop,10,"Arcane, Occult",Transmutation,[three-actions],,,
Spells.aspx?ID=377,Wish,10,Arcane,Divination,[three-actions],,,
`;

let Spells;

function getSpells() {
  if (!Spells) {
    let parseResult = Papa.parse(SpellsData.trim(), { header: true });
    Spells = parseResult.data;
  }

  return Spells;
}
